# Generated by Django 5.1.2 on 2024-11-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
