# Generated by Django 5.1.2 on 2024-11-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_login_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
