# Generated by Django 5.1.3 on 2024-11-12 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_title_task_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='editable_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
