# Generated by Django 5.1.3 on 2024-11-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_project_editors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='editors',
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='myapp.project'),
        ),
    ]
