# Generated by Django 5.1.3 on 2024-11-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_project_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='editable_objects', to='myapp.account'),
        ),
    ]
