# Generated by Django 5.1.3 on 2024-11-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_comment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[(1, 'new'), (2, 'in_progress'), (3, 'done')]),
        ),
    ]
