# Generated by Django 5.1.3 on 2024-11-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('new', 'new'), ('in_progress', 'in_progress'), ('done', 'done')]),
        ),
    ]
