# Generated by Django 5.1.3 on 2024-11-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_task_assignee_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, null=True, related_name='pined_task', to='myapp.account'),
        ),
    ]
