# Generated by Django 5.1.3 on 2024-11-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('in_progress', 'in_progress'), ('done', 'done')], max_length=150),
        ),
    ]
