# Generated by Django 5.1.3 on 2024-11-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='without_assignee',
            field=models.TextField(blank=True, null=True),
        ),
    ]
