# Generated by Django 5.1.3 on 2024-11-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_project_without_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='without_assignee',
        ),
    ]
